HelpDesk.MVC/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HelpDesk.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Informe o usuário")]
        [Display(Name = "Usuário:")]
        public string Usuario { get; set; }

        [Required(ErrorMessage = "Informe a senha")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha:")]
        public string Senha { get; set; }

        [Display(Name = "Lembrar Me")]
        public bool LembrarMe { get; set; }

        public string Nome { get; set; }
    }
}

HelpDesk.MVC/Models/ViewModels/TipoPerfilViewModel.cs
using HelpDesk.MVC.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HelpDesk.Domain.Entities
{
    public class TipoPerfilViewModel
    {
        [Key]
        public int PerfilId { get; set; }
        [Required(ErrorMessage = "Preencha o campo Descrição")]
        [MaxLength(100, ErrorMessage = "Máximo {0} caracteres")]
        public string Descricao { get; set; }

        public int Ativo { get; set; }
        public int UsuarioId { get; set; }
        public virtual IEnumerable<UsuarioViewModel> Usuario { get; set; }
    }
}

HelpDesk.MVC/Models/ViewModels/UsuarioViewModel.cs
using HelpDesk.Domain.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HelpDesk.MVC.Models.ViewModels
{
    public class UsuarioViewModel
    {
        [Key]
        public int UsuarioID { get; set; }

        [Required(ErrorMessage ="Preencha o campo Nome")]
        [MaxLength(150, ErrorMessage ="Máximo {0} caracteres")]
        [MinLength(2, ErrorMessage ="Mínimo {0} caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Preencha o campo Email")]
        [MaxLength(100, ErrorMessage = "Máximo {0} caracteres")]
        [EmailAddress(ErrorMessage ="Digite um e-mail válido")]
        [DisplayName("E-mail")]
        public string Email { get; set; }

        [ScaffoldColumn(false)]
        [DisplayName("Data de Cadastro")]
        public DateTime dtCadastro { get; set; }

        [DisplayName("Data de Nascimento")]
        public DateTime dtNasc { get; set; }

        public bool Ativo { get; set; }
        public int PerfilId { get; set; }

        public virtual TipoPerfilViewModel TipoPerfil { get; set; }

        
    }
}

HelpDesk.MVC/Controllers/Cadastro/UsuarioController.cs
using AutoMapper;
using HelpDesk.Domain.Entities;
using HelpDesk.Infra.Data.Repositories;
using HelpDesk.MVC.Models.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;

namespace HelpDesk.MVC.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly UsuarioRepository _usuarioRepository = new UsuarioRepository();
        private const int _quantMaxLinhasPorPagina = 5;
        public ActionResult Index()
        {
            var usuarioViewModel = Mapper.Map<IEnumerable<Usuario>, IEnumerable<UsuarioViewModel>>(_usuarioRepository.GetAll());
            return View(usuarioViewModel);
        }
        [HttpGet]
        public ActionResult Edit(UsuarioViewModel usuario)
        {
            //if (ModelState.IsValid)
            //{
            //    var usuarioDomain = Mapper.Map<UsuarioViewModel, Usuario>(usuario);
            //    _usuarioRepository.Add(usuarioDomain);
            //}
            //return RedirectToAction("index");
            return View();
        }


    }
}

HelpDesk.MVC/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace HelpDesk.MVC.Controllers
{
    public class ContaController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Logoff()
        {
            return View();
        }
        
        [AllowAnonymous]
        public ActionResult AlterarSenha()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult EsqueciSenha()
        {
            return View();
        }

        private void EnviarEmailRedefinicaoSenha()
        {
            //var callbackUrl = Url.Action("RedefinirSenha", "Conta", new { id = usuario.Id }, protocol: Request.Url.Scheme);
            var client = new SmtpClient()
            {
                Host = ConfigurationManager.AppSettings["EmailServidor"],
                Port = 25,
                EnableSsl = (ConfigurationManager.AppSettings["EmailSsl"] == "S"),
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(
                    ConfigurationManager.AppSettings["EmailUsuario"],
                    ConfigurationManager.AppSettings["EmailSenha"])
            };

            var mensagem = new MailMessage();
            mensagem.From = new MailAddress(ConfigurationManager.AppSettings["EmailOrigem"], "Controle de Estoque - Como Programar Melhor");
            //mensagem.To.Add(usuario.Email);
            mensagem.Subject = "Redefinição de senha";
            //mensagem.Body = string.Format("Redefina a sua senha <a href='{0}'>aqui</a>", callbackUrl);
            mensagem.IsBodyHtml = true;

            client.Send(mensagem);
        }
    }
}

HelpDesk.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelpDesk.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HelpDesk.MVC/Views/Conta/Login.cshtml
@model ControleEstoque.Web.Models.LoginViewModel
@{
    ViewBag.Title = "Login";
}
<div class="container-login">
    <div class="row">
        <h3 class="titulo">Entrar no Sistema</h3>
    </div>
    <div class="row">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Conta", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Usuario, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Usuario, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Usuario, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Senha, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Senha, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-4">
                        @Html.CheckBoxFor(m => m.LembrarMe)
                        @Html.LabelFor(m => m.LembrarMe)
                    </div>
                    <div class="col-md-6" style="text-align:right">
                        @Html.ActionLink("Esqueci minha senha", "EsqueciMinhaSenha", "Conta", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-success" value="Entrar" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

HelpDesk.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HelpDesk.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HelpDesk.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

HelpDesk.MVC/Views/Shared/Erro.cshtml
@model HandleErrorInfo

@{
    ViewBag.Title = "";   
}
<h1 class="text-danger text-center">
    Aconteceu um erro, contacte ao administrador para mais informação.
</h1>

<h2 class="text-center"></h2>

<script>
    $(document)
        .ready(function () {
            setTimeout(function () {
                MsgErro('@Model.Exception.Message');
            }, 1000);
        });

</script>

HelpDesk.MVC/Views/Shared/Menus.cshtml
<section class="sidebar">
    <ul class="sidebar-menu">
        <li class="header">Menu de Navegação</li>
        <li>
            <a href="@(Url.Action("Index","Home"))">
                <i class="fa fa-home fa-fw"></i> <span>Inicio</span>
            </a>
        </li>
        <li>
            <a href="@(Url.Action("","",new{ Area = ""}))">
                <i class="fa fa-user"></i> <span>Usuarios</span>
            </a>
        </li>

        <li>
            <a href="@(Url.Action("","",new{ Area = ""}))">
                <i class="fa fa-th fa-fw"></i> <span>Widgets</span>
                <span class="pull-right-container">
                    <small class="label pull-right bg-green">new</small>
                </span>
            </a>
        </li>

        <li class="treeview">
            <a href="#">
                <i class="fa fa-files-o fa-fw"></i>
                <span>Layout Options</span>
            </a>
            <ul class="treeview-menu">
                <li><a href="@(Url.Action("","",new{ Area = ""}))"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
            </ul>
        </li>

        <li class="treeview">
            <a href="#">
                <i class="fa fa-share"></i> <span>Multilevel</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                <li>
                    <a href="#">
                        <i class="fa fa-circle-o"></i> Level One
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                        <li>
                            <a href="#">
                                <i class="fa fa-circle-o"></i> Level Two
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
            </ul>
        </li>

        @if (User.IsInRole("Role"))
        {

        }


    </ul>
</section>


 

HelpDesk.MVC/Views/Shared/Profile.cshtml
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="~/assets/img/logo.jpg" class="user-image" alt="User Image">
        <span class="hidden-xs">Erikson Melgarejo</span>
    </a>
    <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header">
            <img src="~/assets/img/logo.jpg" class="img-circle" alt="User Image">
            <p>
                Erikson Melgarejo
                <small>eriksonlove@gmail.com</small>
            </p>
        </li>
        <!-- Menu Body -->
        @*<li class="user-body">
            <div class="row">
                <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                </div>
            </div>
        </li>*@
        <!-- Menu Footer-->
        <li class="user-footer">
            <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat"><i class="fa fa-user"></i>&nbsp;Perfil</a>
            </div>
            <div class="pull-right">
                @using (Html.BeginForm("LogOff", "Conta",new{Area =""}))
                {
                    @Html.AntiForgeryToken()
                    <button class="btn btn-default btn-flat" type="submit"><i class="fa fa-sign-out"></i>&nbsp;Sair</button>
                }
            </div>
        </li>
    </ul>
</li>

HelpDesk.MVC/Views/Shared/_Cadastro.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var lista = ViewBag.Lista;
    var titulo = ViewBag.Title;
    ViewBag.Title = "Cadastro de " + ViewBag.Title;
}



@RenderSection("Styles", true)
@RenderBody()

<div id="cadastro">
    <span style="font-size:40px">@ViewBag.Title</span>
    <section id="cadastro_conteudo">
        <div id="cabecalho_grid" class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-2">
                        <a id="btn_incluir" class="btn btn-success" role="button"><i class="glyphicon glyphicon-plus"></i> Incluir</a>
                    </div>
                    <div class="col-md-4">
                        @Html.DropDownList("ddl_tam_pag", (SelectList)ViewBag.ListaTamPag, new { @class = "selectpicker" })
                    </div>
                    <div class="col-md-6">
                        @Html.TextBox("txt_filtro", null, new { @class = "form-control" })
                    </div>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table id="grid_cadastro" class="table table-bordered table-striped table-hover @Html.Raw(lista == null || lista.Count == 0 ? "invisivel" : "")">
                    <thead>
                        <tr>
                            @RenderSection("TituloGrid", true)
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div id="mensagem_grid" @Html.Raw(lista != null && lista.Count > 0 ? "class=\"invisivel\"" : "")>
                    Nenhum registro em @titulo
                </div>
            </div>
        </div>
        @if (ViewBag.QuantPaginas > 1)
        {
            <div class="row">
                <div class="col-md-12">
                    <nav>
                        <ul class="pagination">
                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                            @for (int i = 2; i <= ViewBag.QuantPaginas; i++)
                            {
                                <li class="page-item"><a class="page-link" href="#">@i</a></li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        }
    </section>
</div>
@Html.Hidden("id_cadastro")
<div id="modal_cadastro" class="invisivel" role="dialog">
    <div id="msg_mensagem_aviso" class="text-danger invisivel"></div>
    <fieldset>
        @Html.AntiForgeryToken()
        @RenderSection("CamposCadastro", true)
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="modal-footer">
                        <a id="btn_sair" class="btn btn-default" role="button" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i> Sair</a>
                        <a id="btn_confirmar" class="btn btn-primary" role="button"><i class="glyphicon glyphicon-ok"></i> Salvar</a>
                    </div>
                    <div id="msg_aviso" class="alert alert-warning invisivel">Falta preencher os campos acima.</div>
                    <div id="msg_erro" class="alert alert-danger invisible">Ops! Deus ruim!</div>
                </div>
            </div>
        </div>
    </fieldset>
</div>
@section Scripts{
    <script src="~/Scripts/mustache.min.js"></script>

    <script src="~/Scripts/Cadastro/dBase.js"></script>
    @RenderSection("Scripts", true)

}

HelpDesk.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="~/assets/css/please-wait.css" rel="stylesheet" />
    <script src="~/assets/js/please-wait.min.js"></script>
    <script src="~/assets/js/modernizr.js"></script>
    <script src="~/assets/js/jquery.js"></script>
    <!--[if lt IE 9]>
    <script src="~/assets/js/html5shiv.min.js"></script>
    <script src="~/assets/js/respond.min.js"></script>
    <![endif]-->
</head>
<!-- ADD THE CLASS fixed TO GET A FIXED HEADER AND SIDEBAR LAYOUT -->
<!-- the fixed layout is not compatible with sidebar-mini -->
<body class="hold-transition skin-blue fixed sidebar-mini">
    @*<script type="text/javascript">
        function Splash() {
            var splash = window.pleaseWait({
                logo: "/assets/img/logo.jpg",
                backgroundColor: '#3c8dbc',
                loadingHtml: "<h1 class='loading-message'>Template by Erikson</h1>" +
                '<div class="sk-folding-cube"><div class="sk-cube1 sk-cube" ></div><div class="sk-cube2 sk-cube"></div><div class="sk-cube4 sk-cube"></div><div class="sk-cube3 sk-cube"></div></div>'
            });

            return splash;
        }

        waiter = Splash();
        $(document)
            .ready(function () {
                setTimeout(function () {
                    waiter.finish();
                }, 2000);
            });
    </script>*@
    <!-- Site wrapper -->
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="#" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>H</b>ELP</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Sis</b>HELP</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        @Html.Partial("Profile")
                    </ul>
                </div>
            </nav>
        </header>
        <!-- =============================================== -->
        <aside class="main-sidebar">
            @if (@Request.IsAuthenticated)
            {
                @Html.Partial("Menus")
            }
        </aside>
        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.Subtitle</small>
                </h1>
            </section>
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> @ViewContext.Controller.GetType().Assembly.GetName().Version
            </div>
            <strong>Copyright &copy; @DateTime.Now.Year </strong>
        </footer>
    </div>
    <!-- ./wrapper -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/assets/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/assets/css/skin-blue.min.css" rel="stylesheet" />
    <link href="~/assets/plugins/iCheck/flat/blue.css" rel="stylesheet" />
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/jquery.validate.min.js"></script>
    <script src="~/assets/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <script src="~/assets/plugins/fastclick/fastclick.min.js"></script>
    <script src="~/assets/js/app.min.js"></script>
    <script src="~/assets/js/demo.js"></script>
    <script src="~/assets/js/AdminLTE.js"></script>
    <script src="~/assets/plugins/iCheck/icheck.min.js"></script>
    <script>
        $(document).ready(function () {
            $('input[type="radio"]')
                .iCheck({
                    checkboxClass: 'icheckbox_flat-blue',
                    radioClass: 'iradio_flat-blue',
                    increaseArea: '20%' // optional
                });

            $('input[type="checkbox"]:not(.bootstrap-switch)')
                .iCheck({
                    checkboxClass: 'icheckbox_flat-blue',
                    radioClass: 'iradio_flat-blue',
                    increaseArea: '20%' // optional
                });
        })
    </script>
    @RenderSection("scripts", required: false)
    @{
        if (ViewBag.Erro != null)
        {
            foreach (var m in (List<string>)ViewBag.Erro)
            {
                <script>
                    MsgErro('@m');
                </script>
            }
        }

        if (ViewBag.Ok != null)
        {
            foreach (var m in (List<string>)ViewBag.Ok)
            {
                <script>
                    MsgOk('@m');
                </script>
            }
        }

        if (ViewBag.Info != null)
        {
            foreach (var m in (List<string>)ViewBag.Info)
            {
                <script>
                    MsgInfo('@m');
                </script>
            }
        }

        if (ViewBag.Alerta != null)
        {
            foreach (var m in (List<string>)ViewBag.Alerta)
            {
                <script>
                    MsgAlerta('@m');
                </script>
            }
        }

    }
</body>
</html>

HelpDesk.MVC/Views/Shared/_Pager.cshtml
@model HelpDesk.Domain.Entities.Pager
@*//TODO: Criar script que altera a active page e dispara um callback ao clicar *@

<nav aria-label="">
    <ul class="pagination ">
        @for (int i = 1; i <= (Model.TotalRegisters / Model.PageSize) + (Model.TotalRegisters % Model.PageSize == 0 ? 0 : 1); i++)
        {
            <li class="page-item @(Model.ActivePage == i ? "active": "")" data-page-index="@i.ToString()"><a class="page-link" href="#">@i.ToString()</a></li>
        }
    </ul>
</nav>

HelpDesk.MVC/Views/Shared/_Summary.cshtml
<div class="">
    @*SUMMARY*@
    @{ var summary = Convert.ToInt32(ViewData[HelpDesk.MVC.Resources.ViewData.Summary]); }

    <div class="">
        @Html.Partial("_Pager",
                 new HelpDesk.Domain.Entities.Pager()
                 {
                     TotalRegisters = summary,
                     ActivePage = 1,     //O primeiro valor é sempre 1.
            PageSize = HelpDesk.MVC.App_Start.AppSettingsConfig.ListPageSize
                 })
    </div>

    @*Registros: @summary.ToString("N0")*@

    Exibindo <b>@((HelpDesk.MVC.App_Start.AppSettingsConfig.ListPageSize > @summary ? @summary : HelpDesk.MVC.App_Start.AppSettingsConfig.ListPageSize).ToString("N0"))</b> de <b>@summary.ToString("N0")</b> registros
</div>

HelpDesk.MVC/Views/Usuario/_List.cshtml
@model List<HelpDesk.Domain.Entities.Usuario>

<div class="table-responsive">
    <table class="table table-condensed table-hover table-striped bmw-list">
        <tr>
            <th data-order-field="Descricao">Descrição</th>
            @*Buttons*@
            <th class="button "></th>
        </tr>


        @foreach (var m in Model)
        {
            <tr data-pk="@m.UsuarioID">
                
                <td class="button edit">
                    <a title="Editar" class="RowDefaultButton" href="@(Url.Action("Edit", new { pk = m.UsuarioID, callerUrl = Request.QueryString[HelpDesk.MVC.Resources.ViewData.CallerUrl] }))" data-toggle="tooltip"><i class="fa fa-edit " aria-hidden="true"></i></a> @*RowDefaultButton*@
                </td>
            </tr>
        }
    </table>
</div>